config/routes.rb
Rails.application.routes.draw do
  root 'stories#index'
  resources :stories do
    resources :images
  end
  resources :images do
    resources :sentences
  end
end

app/models/image.rb
class Image< ActiveRecord::Base
  belongs_to :story
  has_many :sentences
  validates :image, :presence => true
  validates :number, :presence => true
  has_attached_file :image, styles: { large: "500x500>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
  belongs_to :story
  belongs_to :image
end

app/models/story.rb
class Story < ActiveRecord::Base
  validates :title, :presence => true

  has_many :sentences
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @story = Story.find(params[:story_id])
    number = rand(0..@story.images.length)
    @image = @story.images.find_by number: number
  end

  def show
    @story = Story.find(params[:story_id])
    @image = @story.images.find(params[:id])
  end

  def create
    @story = Story.find(params[:story_id])

    previous_number = @story.images.last.number
    if previous_number
      number = previous_number + 1
    else
      number = 0
    end

    @image = @story.images.new(image_params)
    @image.number = number
    if @image.save
      @story.save
      redirect_to story_path(@image.story)
      flash[:notice] = "You did it!!!"
    else
      redirect_to story_path(@image.story)
      flash[:alert] = "Please attach a file"
    end
  end


  def destroy
    @story = Story.find(params[:story_id])
    @image = @story.images.find(params[:id])
    @image.destroy
    redirect_to story_path(@story)
  end

  private
  def image_params
    params.require(:image).permit! if params[:image]
  end
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
  def index
    @image = Image.find(params[:image_id])
    @sentences = @image.sentences
    @sentence =  @image.sentences.new
  end

  def create
    @image = Image.find(params[:image_id])
    @sentence = @image.sentences.new(sentence_params)
    if @sentence.save
      redirect_to story_path(@image.story_id)
    else
      redirect_to image_sentences_path(@image)
    end
  end

  private
  def sentence_params
    params.require(:sentence).permit(:text, :user_name)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.all
    @story = Story.new
    render :index
  end

  def show
    @story = Story.find(params[:id])
    @image = @story.images.new
    images = @story.images
    sentences = []
    images.each do |image|
      image.sentences.each do |sentence|
        sentences.push(sentence)
      end
    end
    @sentences = sentences.sort_by { |obj| obj.created_at }
    render :show
  end

  def create
    @story = Story.new(story_params)
    if @story.save
      redirect_to stories_path
    else
      redirect_to stories_path
      flash[:alert] = "Failed."
    end
  end


  private
  def story_params
    params.require(:story).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/_form.html.erb
<%= render('layouts/errors', :object => @image) %>

<%= form_for [@story, @image], url: story_images_path(@story), html: {multipart: true} do |f| %>
<%= f.file_field :image %>
<button type="submit" class="btn btn-link pull-left image-button"><i class='fa fa-plus'></i></button>
<% end %>

app/views/images/index.html.erb
<%= image_tag @image.image(:medium) %>
<br>
<%= link_to "Explore your inspiration", story_image_path(@story, @image)%>
<hr>

app/views/images/show.html.erb
<%= image_tag @image.image(:large) %>
<br>

<div class="pull-left">
<%= link_to raw("<i class='fa fa-trash-o'></i>"), story_image_path(@story, @image),
:data => {:confirm => "Are you sure?",
  :method => "delete"} %>
</div>

<%= link_to "Add a sentence, further your life", image_sentences_path(@image) %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StoryTime</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <link href='https://fonts.googleapis.com/css?family=Quicksand:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="text-center">
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>
  </div>

</body>
</html>

app/views/sentences/_form.html.erb
<%= render('layouts/errors', :object => @image) %>

<%= form_for [@image, @sentence] do |f| %>
<%= f.label :text %>
<%= f.text_field :text %>
<%= f.label :user_name %>
<%= f.text_field :user_name %>
<p><%= f.submit %></p>
<% end %>

app/views/sentences/index.html.erb
<h2>Create a new sentence inspired by this image</h2>

<%= image_tag @image.image(:large) %>

<%= render 'form' %>

app/views/stories/_form.html.erb
<%= render('layouts/errors', :object => @story) %>

<%= form_for @story do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<p><%= f.submit %></p>
<% end %>

app/views/stories/index.html.erb
<div class="jumbotron index-header">
  <h1 class="index-text">This is the story of your life, don't f**k it up.</h1>
  <h2 class="index-text">be open..... be freeee......</h2>
</div>

<% if @stories.any? %>
  <ul class="list-unstyled">
    <% @stories.each do |story| %>
      <li><%= link_to story.title, story_path(story)%></li>
    <% end %>
  </ul>
<% else %>
  <h3>No Stories Yet</h3>
<% end %>






<!-- Button trigger modal -->
<button class="btn btn-link" data-toggle="modal" data-target="#stories">
  <i class="fa fa-plus add-story text-center"></i>
</button>

<!-- Modal -->
<div class="modal fade" id="stories" tabindex="-1" role="dialog" aria-labelledby="storyLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="story">Add Title</h4>
      </div>
      <div class="modal-body">
        <%= render 'form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/stories/show.html.erb
<h2><%= @story.title %></h2>
<% if @story.images.any? %>
  <ul class="list-unstyled">
    <% @sentences.each do |sentence| %>
      <li><%= sentence.text %></li>
    <% end %>
  </ul>
<% else %>
  <p>Add to this tale!!</p>
<% end %>


<%= link_to "Contribute", story_images_path(@story) %>
<hr>

<h4 class="image-label">
  Add an Image
</h4>
<div class="submit-image">
  <%= render 'images/form' %>
</div>